# Generated by Django 6.0.1 on 2026-01-29 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Product Name')),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, unique=True)),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='media/products/', verbose_name='Main Image')),
                ('short_description', models.TextField(blank=True, verbose_name='Short Description')),
                ('full_description', models.TextField(blank=True, verbose_name='Full Description')),
                ('specifications', models.TextField(blank=True, verbose_name='Specifications')),
                ('rating', models.DecimalField(decimal_places=1, default=0.0, max_digits=3, verbose_name='Rating')),
                ('review_count', models.PositiveIntegerField(default=0, verbose_name='Number of Reviews')),
                ('category', models.CharField(blank=True, max_length=100, verbose_name='Category (e.g. Headphones)')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Featured Product?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['-created_at'],
            },
        ),
    ]
